/*
===============================================================================
Project Name : Retail Sales Analytics using SQL

File Name    : 02_Exploratory_Data_Analysis.sql

Description  :
This file contains exploratory data analysis (EDA) queries used to
understand sales trends, pricing, customer activity and transaction patterns
before performing business analysis.

===============================================================================
*/

USE retail_analytics;

/*
--------------------------------------------------------------------------------
Business Question:
What is the total revenue generated by the company?
--------------------------------------------------------------------------------
*/
select round(sum(QuantityPurchased * Price),2) as Total_Revenue
from sales_transaction_clean;

/*
--------------------------------------------------------------------------------
Business Question:
How many total units have been sold?
--------------------------------------------------------------------------------
*/
select round(sum(QuantityPurchased),2) as Total_Units_Sold
from sales_transaction_clean;

/*
--------------------------------------------------------------------------------
Business Question:
What is the average selling price of products?
--------------------------------------------------------------------------------
*/
select round(avg(Price),2) as Average_Price
from sales_transaction_clean;

/*
--------------------------------------------------------------------------------
Business Question:
What is the highest selling price recorded?
--------------------------------------------------------------------------------
*/
select max(Price) as Highest_Price
from sales_transaction_clean;

/*
--------------------------------------------------------------------------------
Business Question:
What is the lowest selling price recorded?
--------------------------------------------------------------------------------
*/
select min(Price) as Lowest_Price
from sales_transaction_clean;

/*
------------------------------------------------------------------------------
Business Question:
Which products generate the highest total revenue?
------------------------------------------------------------------------------
*/
select ProductID, round(sum(QuantityPurchased * Price),2) as Total_Revenue
from sales_transaction_clean
group by ProductID
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
Which products generate the lowest total revenue?
------------------------------------------------------------------------------
*/
select ProductID, round(sum(QuantityPurchased * Price),2) as Total_Revenue
from sales_transaction_clean
group by ProductID
order by Total_Revenue asc;

/*
------------------------------------------------------------------------------
Business Question:
Which products have sold the highest quantity?
------------------------------------------------------------------------------
*/
select ProductId, sum(QuantityPurchased) as Total_Quantity_Sold
from sales_transaction_clean
group by ProductID
order by Total_Quantity_Sold desc;

/*
------------------------------------------------------------------------------
Business Question:
Which products have sold the lowest quantity?
------------------------------------------------------------------------------
*/
select ProductId, sum(QuantityPurchased) as Total_Quantity_Sold
from sales_transaction_clean
group by ProductID
order by Total_Quantity_Sold asc;


/*
------------------------------------------------------------------------------
Business Question:
Which customers generated the highest total revenue?
------------------------------------------------------------------------------
*/
select CustomerID, round(sum(QuantityPurchased * Price),2) as Total_Revenue
from sales_transaction_clean
group by CustomerID
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
Which customers purchased the highest quantity of products?
------------------------------------------------------------------------------
*/
select CustomerID, sum(QuantityPurchased) as Total_Quantity_Sold
from sales_transaction_clean
group by CustomerID
order by Total_Quantity_Sold desc;

/*
------------------------------------------------------------------------------
Business Question:
Which customers made the highest number of transactions?
------------------------------------------------------------------------------
*/
select CustomerID, count(TransactionID) as Total_Transactions
from sales_transaction_clean
group by CustomerID
order by Total_Transactions desc;

/*
------------------------------------------------------------------------------
Business Question:
Which customers have made repeat purchases?
------------------------------------------------------------------------------
*/
select CustomerID, count(TransactionID) as Total_Transactions
from sales_transaction_clean
group by CustomerID
having Total_Transactions>1;

/*
------------------------------------------------------------------------------
Business Question:
How does total revenue vary across different months?
------------------------------------------------------------------------------
*/
select monthname(TransactionDate) as Month, round(sum(QuantityPurchased * Price),2) as Total_Revenue
from sales_transaction_clean
group by monthname(TransactionDate), month(TransactionDate)
order by month(TransactionDate);

/*
------------------------------------------------------------------------------
Business Question:
Which day of the week generates the highest revenue?
------------------------------------------------------------------------------
*/
select dayname(TransactionDate) as Day, round(sum(QuantityPurchased * Price),2) as Total_Revenue
from sales_transaction_clean
group by dayname(TransactionDate)
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
How does total revenue vary across different years?
------------------------------------------------------------------------------
*/
select year(TransactionDate) as Year, round(sum(QuantityPurchased * Price),2) as Total_Revenue
from sales_transaction_clean
group by year(TransactionDate)
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
Which quarter generates the highest revenue?
------------------------------------------------------------------------------
*/
select concat('Q',quarter(TransactionDate)) as Quarter, round(sum(QuantityPurchased * Price),2) as Total_Revenue
from sales_transaction_clean
group by Quarter
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
What is the date range and transaction count for each quarter?
------------------------------------------------------------------------------
*/
select
    quarter(TransactionDate) as Quarter,
    min(TransactionDate) as Start_Date,
    max(TransactionDate) as End_Date,
    count(*) as Total_Transactions
from sales_transaction_clean
group by quarter(TransactionDate)
order by quarter;

/*
------------------------------------------------------------------------------
Business Question:
What is the overall transaction date range available in the dataset?
------------------------------------------------------------------------------
*/
select min(TransactionDate) as Start_Date,
       max(TransactionDate) as End_Date
from sales_transaction_clean;

/*
------------------------------------------------------------------------------
Business Question:
What is the transaction date range and transaction count for each quarter?
------------------------------------------------------------------------------
*/
select quarter(TransactionDate) as Quarter,
       min(TransactionDate) as Start_Date,
       max(TransactionDate) as End_Date,
       count(TransactionID) as Total_Transactions
from sales_transaction_clean
group by quarter(TransactionDate)
order by Quarter;