/*
===============================================================================
Project Name : Retail Sales Analytics using SQL

File Name    : 03_Business_Analysis.sql

Description  :
This file contains SQL queries that solve key business problems related to
product performance, customer segmentation, and customer behaviour analysis.

===============================================================================
*/

USE retail_analytics;

/*
===============================================================================
SECTION 1 : PRODUCT PERFORMANCE ANALYSIS
===============================================================================
*/

/*
------------------------------------------------------------------------------
Business Question:
Which product categories generate the highest total revenue?
------------------------------------------------------------------------------
*/
select pi.Category, round(sum(st.QuantityPurchased * st.Price),2) as Total_Revenue
from sales_transaction_clean st
join product_inventory pi
	on st.ProductID = pi.ProductID
group by pi.Category
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
Which are the top 5 highest revenue-generating products?
------------------------------------------------------------------------------
*/
select pi.ProductName, pi.Category, round(sum(st.QuantityPurchased * st.Price),2) as Total_Revenue
from sales_transaction_clean st
join product_inventory pi
	on st.ProductID = pi.ProductID
group by pi.Category, pi.ProductName
order by Total_Revenue desc
limit 5;

/*
------------------------------------------------------------------------------
Business Question:
Which customer locations contribute the highest total revenue?
------------------------------------------------------------------------------
*/
select cp.Location, count(st.TransactionID) as Total_Transaction, round(sum(st.QuantityPurchased * st.Price),2) as Total_Revenue
from sales_transaction_clean st
join customer_profiles cp
	on st.CustomerID = cp.CustomerID
where cp.Location is not null
and cp.Location <> ''
group by cp.Location
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
Which product category generates the highest revenue in each customer location?
------------------------------------------------------------------------------
*/
with Aggregate as
(
	select cp.Location, pi.Category, round(sum(st.QuantityPurchased * st.Price),2) as Total_Revenue
	from sales_transaction_clean st
	join customer_profiles cp
		on st.CustomerID = cp.CustomerID
	join product_inventory pi
		on st.ProductID = pi.ProductID
	where cp.Location is not null
		and cp.Location <> ''
	group by pi.Category, cp.Location
),
Ranking as
(
select *, 
dense_rank() over(
	partition by Location
    order by Total_Revenue desc
) as ranks	
from Aggregate
)
select * from Ranking
where ranks = 1;

/*
------------------------------------------------------------------------------
Business Question:
How many times has each product been sold?
------------------------------------------------------------------------------
*/
select pi.ProductID, pi.ProductName, pi.Category, count(st.TransactionID) as Total_Times_Sold
from product_inventory pi
left join sales_transaction_clean st
	on pi.ProductID = st.ProductID
group by pi.ProductID, pi.ProductName, pi.Category;

/*
------------------------------------------------------------------------------
Business Question:
What are the total units sold and total revenue generated by each product?
------------------------------------------------------------------------------
*/
select pi.ProductID, pi.ProductName, pi.Category,
	coalesce(sum(st.QuantityPurchased),0) as Total_Units_Sold, coalesce(round(sum(st.QuantityPurchased * st.Price),2),0) as Total_Revenue
from product_inventory pi
left join sales_transaction_clean st
	on pi.ProductID = st.ProductID
group by pi.ProductID, pi.ProductName, pi.Category
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
Which products have never been sold?
------------------------------------------------------------------------------
Note:
All 200 products in the current dataset have at least one sale.
Therefore, this query returns zero rows.
------------------------------------------------------------------------------
*/
select pi.ProductID, pi.ProductName, pi.Category, pi.StockLevel
from product_inventory pi
left join sales_transaction_clean st
	on pi.ProductID = st.ProductID
where st.TransactionID is null;


/*
===============================================================================
SECTION 2 : CUSTOMER SEGMENTATION
===============================================================================
*/
/*
------------------------------------------------------------------------------
Business Question:
How can customers be segmented based on the total quantity of products they
have purchased?
------------------------------------------------------------------------------
*/
with CustomerPurchase as
(
	select cp.CustomerID, coalesce(sum(st.QuantityPurchased),0) as Total_Units_Purchased
    from customer_profiles cp
	left join sales_transaction_clean st
		on cp.CustomerID = st.CustomerID 
	group by cp.CustomerID
)
select CustomerID,
	   Total_Units_Purchased,
case
	when Total_Units_Purchased = 0 then 'No Orders'
    when Total_Units_Purchased <= 10 then 'Low'
    when Total_Units_Purchased <= 30 then 'Mid'
    else 'High Value'
end as Customer_Segment
from CustomerPurchase;

/*
------------------------------------------------------------------------------
Business Question:
How many customers belong to each customer segment?
------------------------------------------------------------------------------
*/
with Segmentation as
(
select cp.CustomerID, 
case
	when coalesce(sum(st.QuantityPurchased),0) = 0 then 'No Orders'
    when coalesce(sum(st.QuantityPurchased),0) <= 10 then 'Low'
    when coalesce(sum(st.QuantityPurchased),0) <= 30 then 'Mid'
    else 'High Value'
end as Customer_Segment
from customer_profiles cp
left join sales_transaction_clean st
	on cp.CustomerID = st.CustomerID
group by cp.CustomerID
)
select Customer_Segment,
	count(CustomerID) as Number_of_Customers
    from Segmentation
    group by Customer_Segment;


/*
===============================================================================
SECTION 3 : CUSTOMER BEHAVIOUR ANALYSIS
===============================================================================
*/

/*
------------------------------------------------------------------------------
Business Question:
Who are the top 10 highest spending customers based on total revenue?
------------------------------------------------------------------------------
*/
with CustInfo as
(
	select cp.CustomerID, cp.Gender, cp.Location, round(sum(st.QuantityPurchased * st.Price),2) as Total_Revenue
    from customer_profiles cp
    left join sales_transaction_clean st
		on cp.CustomerID = st.CustomerID
	group by cp.CustomerID, cp.Gender, cp.Location
),
CustRank as
(
	select *, dense_rank() over (
            order by Total_Revenue desc
		) as Revenue_Rank
	from CustInfo
)
select * from CustRank
where Revenue_Rank <= 10;

/*
------------------------------------------------------------------------------
Business Question:
Which customers have made the highest number of transactions?
------------------------------------------------------------------------------
*/
with Cust_Transaction as
(
	select cp.CustomerID, cp.Gender, cp.Location, count(st.TransactionID) as Total_Transactions
    from customer_profiles cp
    left join sales_transaction_clean st
		on cp.CustomerID = st.CustomerID
	group by cp.CustomerID, cp.Gender, cp.Location
),
Cust_Ranking as
(
	select *,
		dense_rank() over (
			order by Total_Transactions desc
		) as Transaction_Rank
	from Cust_Transaction
)
select * from Cust_Ranking
where Transaction_Rank <= 10;

/*
------------------------------------------------------------------------------
Business Question:
How does total revenue vary by customer gender?
------------------------------------------------------------------------------
*/
select cp.Gender, round(sum(st.QuantityPurchased * st.Price),2) as Total_Revenue
from customer_profiles cp
left join sales_transaction_clean st
	on cp.CustomerID = st.CustomerID
group by cp.Gender
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
Which customer age groups contribute the highest total revenue?
------------------------------------------------------------------------------
*/
select 
case
	when cp.Age < 20 then 'Teen'
    when cp.Age <= 35 then 'Young Adult'
    when cp.Age <= 50 then 'Adult'
    else 'Senior'
end as Age_Group,
round(sum(st.QuantityPurchased * st.Price),2) as Total_Revenue
from customer_profiles cp
left join sales_transaction_clean st
	on cp.CustomerID = st.CustomerID
group by Age_Group
order by Total_Revenue desc;

/*
------------------------------------------------------------------------------
Business Question:
What is the average order value (AOV) across all transactions?
------------------------------------------------------------------------------
*/
select (round(sum(QuantityPurchased * Price) / 
		count(TransactionID),2)) as Average_Order_Value
from sales_transaction_clean;

/*
------------------------------------------------------------------------------
Business Question:
Which customers have placed more than one order?
------------------------------------------------------------------------------
*/
select cp.CustomerID, count(st.TransactionID) as Total_Transactions
from customer_profiles cp
left join sales_transaction_clean st
	on cp.CustomerID = st.CustomerID
group by cp.CustomerID
having Total_Transactions > 1;

/*
------------------------------------------------------------------------------
Business Question:
How can customers be ranked based on loyalty using total transactions and
total revenue?
------------------------------------------------------------------------------
*/
with Cust_Info as
(
	select cp.CustomerID, cp.Gender, cp.Location, count(st.TransactionId) as Total_Transaction, 
			round(sum(st.QuantityPurchased * st.Price),2) as Total_Revenue
	from customer_profiles cp
    left join sales_transaction_clean st
		on cp.CustomerID = st.CustomerID
	group by cp.CustomerID, cp.Gender, cp.Location
)
select *, dense_rank() over (
			order by Total_Transaction desc, Total_Revenue desc
		) as Loyalty_Rank
from Cust_Info;

/*
------------------------------------------------------------------------------
Business Question:
What percentage of customers are repeat customers?
------------------------------------------------------------------------------
*/
select 
    round(
        sum(case when Total_Transactions > 1 then 1 else 0 end) * 100.0 
        / count(*), 2
    ) as Repeat_Customer_Percentage
from (
    select CustomerID, count(TransactionID) as Total_Transactions
    from sales_transaction_clean
    group by CustomerID
) as T;